/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jfprint_DiscoveredDevice */

#ifndef _Included_jfprint_DiscoveredDevice
#define _Included_jfprint_DiscoveredDevice
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jfprint_DiscoveredDevice
 * Method:    nativeClose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jfprint_DiscoveredDevice_nativeClose
  (JNIEnv *, jobject);

/*
 * Class:     jfprint_DiscoveredDevice
 * Method:    fp_open
 * Signature: ()Ljfprint/Device;
 */
JNIEXPORT jobject JNICALL Java_jfprint_DiscoveredDevice_fp_1open
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
