/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jfprint_FpDevice */

#ifndef _Included_jfprint_FpDevice
#define _Included_jfprint_FpDevice
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jfprint_FpDevice
 * Method:    nativeClose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jfprint_FpDevice_nativeClose
  (JNIEnv *, jobject);

/*
 * Class:     jfprint_FpDevice
 * Method:    get_driver
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jfprint_FpDevice_get_1driver
  (JNIEnv *, jobject);

/*
 * Class:     jfprint_FpDevice
 * Method:    get_device_id
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jfprint_FpDevice_get_1device_1id
  (JNIEnv *, jobject);

/*
 * Class:     jfprint_FpDevice
 * Method:    get_name
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jfprint_FpDevice_get_1name
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
