/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jfprint_FpDevice */

#ifndef _Included_jfprint_FpDevice
#define _Included_jfprint_FpDevice
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jfprint_FpDevice
 * Method:    nativeClose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jfprint_FpDevice_nativeClose
  (JNIEnv *, jobject);

/*
 * Class:     jfprint_FpDevice
 * Method:    native_get_driver
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jfprint_FpDevice_native_1get_1driver
  (JNIEnv *, jobject);

/*
 * Class:     jfprint_FpDevice
 * Method:    native_get_device_id
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jfprint_FpDevice_native_1get_1device_1id
  (JNIEnv *, jobject);

/*
 * Class:     jfprint_FpDevice
 * Method:    native_get_name
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jfprint_FpDevice_native_1get_1name
  (JNIEnv *, jobject);

/*
 * Class:     jfprint_FpDevice
 * Method:    native_open
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jfprint_FpDevice_native_1open
  (JNIEnv *, jobject);

/*
 * Class:     jfprint_FpDevice
 * Method:    native_close
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jfprint_FpDevice_native_1close
  (JNIEnv *, jobject);

/*
 * Class:     jfprint_FpDevice
 * Method:    native_enroll
 * Signature: (Ljfprint/util/EnrollProgressInterface;Ljfprint/TemplatePrint;)Ljfprint/FpPrint;
 */
JNIEXPORT jobject JNICALL Java_jfprint_FpDevice_native_1enroll
  (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
