/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jfprint_Img */

#ifndef _Included_jfprint_Img
#define _Included_jfprint_Img
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jfprint_Img
 * Method:    nativeClose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jfprint_Img_nativeClose
  (JNIEnv *, jobject);

/*
 * Class:     jfprint_Img
 * Method:    fp_getHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jfprint_Img_fp_1getHeight
  (JNIEnv *, jobject);

/*
 * Class:     jfprint_Img
 * Method:    fp_getWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jfprint_Img_fp_1getWidth
  (JNIEnv *, jobject);

/*
 * Class:     jfprint_Img
 * Method:    fp_getData
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_jfprint_Img_fp_1getData
  (JNIEnv *, jobject);

/*
 * Class:     jfprint_Img
 * Method:    fp_saveToFile
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_jfprint_Img_fp_1saveToFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     jfprint_Img
 * Method:    fp_standardize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jfprint_Img_fp_1standardize
  (JNIEnv *, jobject);

/*
 * Class:     jfprint_Img
 * Method:    fp_binarize
 * Signature: ()Ljfprint/Img;
 */
JNIEXPORT jobject JNICALL Java_jfprint_Img_fp_1binarize
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
