/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jfprint_FpPrint */

#ifndef _Included_jfprint_FpPrint
#define _Included_jfprint_FpPrint
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jfprint_FpPrint
 * Method:    nativeClose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jfprint_FpPrint_nativeClose
  (JNIEnv *, jobject);

/*
 * Class:     jfprint_FpPrint
 * Method:    native_get_finger
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jfprint_FpPrint_native_1get_1finger
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
