/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jfprint_Core */

#ifndef _Included_jfprint_Core
#define _Included_jfprint_Core
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jfprint_Core
 * Method:    fp_init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jfprint_Core_fp_1init
  (JNIEnv *, jclass);

/*
 * Class:     jfprint_Core
 * Method:    fp_exit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jfprint_Core_fp_1exit
  (JNIEnv *, jclass);

/*
 * Class:     jfprint_Core
 * Method:    fp_set_debug
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jfprint_Core_fp_1set_1debug
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
