/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jfprint_FpContext */

#ifndef _Included_jfprint_FpContext
#define _Included_jfprint_FpContext
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jfprint_FpContext
 * Method:    nativeClose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jfprint_FpContext_nativeClose
  (JNIEnv *, jobject);

/*
 * Class:     jfprint_FpContext
 * Method:    native_context_new
 * Signature: ()Ljfprint/FpContext;
 */
JNIEXPORT jobject JNICALL Java_jfprint_FpContext_native_1context_1new
  (JNIEnv *, jclass);

/*
 * Class:     jfprint_FpContext
 * Method:    native_n_devices
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jfprint_FpContext_native_1n_1devices
  (JNIEnv *, jobject);

/*
 * Class:     jfprint_FpContext
 * Method:    native_get_device
 * Signature: (I)Ljfprint/FpDevice;
 */
JNIEXPORT jobject JNICALL Java_jfprint_FpContext_native_1get_1device
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
