/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jfprint_DiscoveredPrintList */

#ifndef _Included_jfprint_DiscoveredPrintList
#define _Included_jfprint_DiscoveredPrintList
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jfprint_DiscoveredPrintList
 * Method:    nativeClose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jfprint_DiscoveredPrintList_nativeClose
  (JNIEnv *, jobject);

/*
 * Class:     jfprint_DiscoveredPrintList
 * Method:    fp_get
 * Signature: (I)Ljfprint/DiscoveredPrint;
 */
JNIEXPORT jobject JNICALL Java_jfprint_DiscoveredPrintList_fp_1get
  (JNIEnv *, jobject, jint);

/*
 * Class:     jfprint_DiscoveredPrintList
 * Method:    fp_discoverPrints
 * Signature: ()Ljfprint/DiscoveredPrintList;
 */
JNIEXPORT jobject JNICALL Java_jfprint_DiscoveredPrintList_fp_1discoverPrints
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
