/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jfprint_DiscoveredPrint */

#ifndef _Included_jfprint_DiscoveredPrint
#define _Included_jfprint_DiscoveredPrint
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jfprint_DiscoveredPrint
 * Method:    nativeClose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jfprint_DiscoveredPrint_nativeClose
  (JNIEnv *, jobject);

/*
 * Class:     jfprint_DiscoveredPrint
 * Method:    fp_getDriverId
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jfprint_DiscoveredPrint_fp_1getDriverId
  (JNIEnv *, jobject);

/*
 * Class:     jfprint_DiscoveredPrint
 * Method:    fp_getDevtype
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jfprint_DiscoveredPrint_fp_1getDevtype
  (JNIEnv *, jobject);

/*
 * Class:     jfprint_DiscoveredPrint
 * Method:    fp_getFinger
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jfprint_DiscoveredPrint_fp_1getFinger
  (JNIEnv *, jobject);

/*
 * Class:     jfprint_DiscoveredPrint
 * Method:    fp_delete
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jfprint_DiscoveredPrint_fp_1delete
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
