/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jfprint_Device */

#ifndef _Included_jfprint_Device
#define _Included_jfprint_Device
#ifdef __cplusplus
extern "C" {
#endif
#undef jfprint_Device_FP_ENROLL_COMPLETE
#define jfprint_Device_FP_ENROLL_COMPLETE 1L
#undef jfprint_Device_FP_ENROLL_FAIL
#define jfprint_Device_FP_ENROLL_FAIL 2L
#undef jfprint_Device_FP_ENROLL_PASS
#define jfprint_Device_FP_ENROLL_PASS 3L
#undef jfprint_Device_FP_ENROLL_RETRY
#define jfprint_Device_FP_ENROLL_RETRY 100L
#undef jfprint_Device_FP_ENROLL_RETRY_TOO_SHORT
#define jfprint_Device_FP_ENROLL_RETRY_TOO_SHORT 101L
#undef jfprint_Device_FP_ENROLL_RETRY_CENTER_FINGER
#define jfprint_Device_FP_ENROLL_RETRY_CENTER_FINGER 102L
#undef jfprint_Device_FP_ENROLL_RETRY_REMOVE_FINGER
#define jfprint_Device_FP_ENROLL_RETRY_REMOVE_FINGER 103L
#undef jfprint_Device_FP_VERIFY_NO_MATCH
#define jfprint_Device_FP_VERIFY_NO_MATCH 0L
#undef jfprint_Device_FP_VERIFY_MATCH
#define jfprint_Device_FP_VERIFY_MATCH 1L
#undef jfprint_Device_FP_VERIFY_RETRY
#define jfprint_Device_FP_VERIFY_RETRY 100L
#undef jfprint_Device_FP_VERIFY_RETRY_TOO_SHORT
#define jfprint_Device_FP_VERIFY_RETRY_TOO_SHORT 101L
#undef jfprint_Device_FP_VERIFY_RETRY_CENTER_FINGER
#define jfprint_Device_FP_VERIFY_RETRY_CENTER_FINGER 102L
#undef jfprint_Device_FP_VERIFY_RETRY_REMOVE_FINGER
#define jfprint_Device_FP_VERIFY_RETRY_REMOVE_FINGER 103L
/*
 * Class:     jfprint_Device
 * Method:    nativeClose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jfprint_Device_nativeClose
  (JNIEnv *, jobject);

/*
 * Class:     jfprint_Device
 * Method:    fp_getDriver
 * Signature: ()Ljfprint/Driver;
 */
JNIEXPORT jobject JNICALL Java_jfprint_Device_fp_1getDriver
  (JNIEnv *, jobject);

/*
 * Class:     jfprint_Device
 * Method:    fp_getNumEnrollStages
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jfprint_Device_fp_1getNumEnrollStages
  (JNIEnv *, jobject);

/*
 * Class:     jfprint_Device
 * Method:    fp_getDevType
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jfprint_Device_fp_1getDevType
  (JNIEnv *, jobject);

/*
 * Class:     jfprint_Device
 * Method:    fp_supportsPrintData
 * Signature: (Ljfprint/PrintData;)Z
 */
JNIEXPORT jboolean JNICALL Java_jfprint_Device_fp_1supportsPrintData
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jfprint_Device
 * Method:    fp_supportsDiscoveredPrint
 * Signature: (Ljfprint/DiscoveredPrint;)Z
 */
JNIEXPORT jboolean JNICALL Java_jfprint_Device_fp_1supportsDiscoveredPrint
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jfprint_Device
 * Method:    fp_supportsImaging
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jfprint_Device_fp_1supportsImaging
  (JNIEnv *, jobject);

/*
 * Class:     jfprint_Device
 * Method:    fp_supportsIdentification
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jfprint_Device_fp_1supportsIdentification
  (JNIEnv *, jobject);

/*
 * Class:     jfprint_Device
 * Method:    fp_imgCapture
 * Signature: (Z)Ljfprint/Img;
 */
JNIEXPORT jobject JNICALL Java_jfprint_Device_fp_1imgCapture
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     jfprint_Device
 * Method:    fp_getImgWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jfprint_Device_fp_1getImgWidth
  (JNIEnv *, jobject);

/*
 * Class:     jfprint_Device
 * Method:    fp_getImgHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jfprint_Device_fp_1getImgHeight
  (JNIEnv *, jobject);

/*
 * Class:     jfprint_Device
 * Method:    fp_enrollFingerImg
 * Signature: (Ljfprint/util/Wrapper;Ljfprint/util/Wrapper;)I
 */
JNIEXPORT jint JNICALL Java_jfprint_Device_fp_1enrollFingerImg
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     jfprint_Device
 * Method:    fp_verifyFingerImg
 * Signature: (Ljfprint/PrintData;Ljfprint/util/Wrapper;)I
 */
JNIEXPORT jint JNICALL Java_jfprint_Device_fp_1verifyFingerImg
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     jfprint_Device
 * Method:    fp_identifyFingerImg
 * Signature: (Ljfprint/util/Wrapper;[Ljfprint/PrintData;)Ljfprint/util/ResultTuple;
 */
JNIEXPORT jobject JNICALL Java_jfprint_Device_fp_1identifyFingerImg
  (JNIEnv *, jobject, jobject, jobjectArray);

/*
 * Class:     jfprint_Device
 * Method:    fp_enrollFinger
 * Signature: (Ljfprint/util/Wrapper;)I
 */
JNIEXPORT jint JNICALL Java_jfprint_Device_fp_1enrollFinger
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jfprint_Device
 * Method:    fp_verifyFinger
 * Signature: (Ljfprint/PrintData;)I
 */
JNIEXPORT jint JNICALL Java_jfprint_Device_fp_1verifyFinger
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jfprint_Device
 * Method:    fp_identifyFinger
 * Signature: ([Ljfprint/PrintData;)Ljfprint/util/ResultTuple;
 */
JNIEXPORT jobject JNICALL Java_jfprint_Device_fp_1identifyFinger
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
